base_config:
  - configs/basics/fs2.yaml

task_cls: src.diffsinger_task.DiffSingerMIDITask
datasets: [
  'opencpop',
]
num_spk: 1
test_prefixes: [
    '2044',
    '2086',
    '2092',
    '2093',
    '2100',
]

test_num: 0
valid_num: 0

pre_align_cls: data_gen.pre_align.SingingPreAlign
pre_align_args:
  txt_processor: zh_g2pM
  use_tone: false # for ZH
  forced_align: mfa
  use_sox: true
max_frames: 8000

audio_sample_rate: 24000
hop_size: 128            # Hop size.
fft_size: 512           # FFT size.
win_size: 512           # FFT size.
fmin: 30
fmax: 12000
min_level_db: -120

vocoder: src.vocoders.hifigan.HifiGAN
vocoder_ckpt: checkpoints/0109_hifigan_bigpopcs_hop128
use_nsf: true

binarizer_cls: data_gen.opencpop.OpencpopBinarizer
binarization_args:
  with_wav: true
  with_spk_embed: false
  with_align: true
raw_data_dir: 'data/raw/opencpop/segments'
processed_data_dir: 'xxx'
binary_data_dir: 'data/binary/opencpop-midi-dp'
save_f0: true

pitch_extractor: 'parselmouth'
pitch_type: frame
# config for experiments
use_spk_embed: false
num_valid_plots: 10
lr: 0.001

content_cond_steps: [ ] # [ 0, 10000 ]
spk_cond_steps: [ ] # [ 0, 10000 ]

#switch_midi2f0_step: 174000
use_midi: true  #  for midi exp
use_gt_dur: false  # for further midi exp
use_spk_id: false
use_pitch_embed: false

lambda_ph_dur: 1.0
lambda_sent_dur: 1.0
lambda_word_dur: 1.0
predictor_grad: 0.1
dur_predictor_layers: 5  # *
mel_vmin: -6. #-6.
mel_vmax: 1.5
wav2spec_eps: 1e-6
spec_min: [-6., -6., -6., -6., -6., -6., -6., -6., -6., -6., -6., -6.,
           -6., -6., -6., -6., -6., -6., -6., -6., -6., -6., -6., -6.,
           -6., -6., -6., -6., -6., -6., -6., -6., -6., -6., -6., -6.,
           -6., -6., -6., -6., -6., -6., -6., -6., -6., -6., -6., -6.,
           -6., -6., -6., -6., -6., -6., -6., -6., -6., -6., -6., -6.,
           -6., -6., -6., -6., -6., -6., -6., -6., -6., -6., -6., -6.,
           -6., -6., -6., -6., -6., -6., -6., -6.]
spec_max: [-7.9453e-01, -8.1116e-01, -6.1631e-01, -3.0679e-01, -1.3863e-01,
           -5.0652e-02, -1.1563e-01, -1.0679e-01, -9.1068e-02, -6.2174e-02,
           -7.5302e-02, -7.2217e-02, -6.3815e-02, -7.3299e-02,  7.3610e-03,
           -7.2508e-02, -5.0234e-02, -1.6534e-01, -2.6928e-01, -2.0782e-01,
           -2.0823e-01, -1.1702e-01, -7.0128e-02, -6.5868e-02, -1.2675e-02,
           1.5121e-03, -8.9902e-02, -2.1392e-01, -2.3789e-01, -2.8922e-01,
           -3.0405e-01, -2.3029e-01, -2.2088e-01, -2.1542e-01, -2.9367e-01,
           -3.0137e-01, -3.8281e-01, -4.3590e-01, -2.8681e-01, -4.6855e-01,
           -5.7485e-01, -4.7022e-01, -5.4266e-01, -4.4848e-01, -6.4120e-01,
           -6.8700e-01, -6.4860e-01, -7.6436e-01, -4.9971e-01, -7.1068e-01,
           -6.9724e-01, -6.1487e-01, -5.5843e-01, -6.9773e-01, -5.7502e-01,
           -7.0919e-01, -8.2431e-01, -8.4213e-01, -9.0431e-01, -8.2840e-01,
           -7.7945e-01, -8.2758e-01, -8.7699e-01, -1.0532e+00, -1.0766e+00,
           -1.1198e+00, -1.0185e+00, -9.8983e-01, -1.0001e+00, -1.0756e+00,
           -1.0024e+00, -1.0304e+00, -1.0579e+00, -1.0188e+00, -1.0500e+00,
           -1.0842e+00, -1.0923e+00, -1.1223e+00, -1.2381e+00, -1.6467e+00]

fs2_ckpt: ''  #
#num_valid_plots: 0

# for diffusion schedule
timesteps: 1000
K_step: 1000
max_beta: 0.02
max_tokens: 36000
max_updates: 320000
gaussian_start: True
pndm_speedup: 40

diff_loss_type: l1
diff_decoder_type: 'wavenet'
schedule_type: 'linear'

mel_loss: "ssim:0.5|l1:0.5"
hidden_size: 256
residual_layers: 20
residual_channels: 256
decay_steps: 50000
keep_bins: 80

use_gt_f0: false  #  for midi exp

lambda_f0: 0.
lambda_uv: 0.
lambda_energy: 0.0
dilation_cycle_length: 4  # *
rel_pos: true
predictor_layers: 5
pe_enable: true
pe_ckpt: 'checkpoints/0102_xiaoma_pe'

# train and eval
# max_updates: 200000
gen_tgt_spk_id: -1
max_sentences: 48
num_sanity_val_steps: 1
